<a href="https://colab.research.google.com/github/AtulAravindDas/FinVAR/blob/main/Datasetcreation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [146]:
import pandas as pd
import numpy as np

In [147]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# **Cleaning the EPS dataset(obtained it from Compustat Fundamental Annual page)**

In [148]:
df=pd.read_csv('/content/drive/MyDrive/ticker_eps.csv')

In [149]:
df

datadate  fyear datafmt  tic  epspx
0     12/31/15   2015     STD  ABT   1.73
1     12/31/16   2016     STD  ABT   0.71
2     12/31/17   2017     STD  ABT   0.20
3     12/31/18   2018     STD  ABT   1.32
4     12/31/19   2019     STD  ABT   2.07
...        ...    ...     ...  ...    ...
2279  12/31/20   2020     STD  LYB   4.25
2280  12/31/21   2021     STD  LYB  16.79
2281  12/31/22   2022     STD  LYB  11.86
2282  12/31/23   2023     STD  LYB   6.50
2283  12/31/24   2024     STD  LYB   4.15

[2284 rows x 5 columns]

In [150]:
df.isnull().sum()

datadate      0
fyear         0
datafmt       0
tic           0
epspx       275
dtype: int64

In [151]:
df=df.dropna()

In [152]:
new_df=df
new_df

datadate  fyear datafmt  tic  epspx
0     12/31/15   2015     STD  ABT   1.73
1     12/31/16   2016     STD  ABT   0.71
2     12/31/17   2017     STD  ABT   0.20
3     12/31/18   2018     STD  ABT   1.32
4     12/31/19   2019     STD  ABT   2.07
...        ...    ...     ...  ...    ...
2279  12/31/20   2020     STD  LYB   4.25
2280  12/31/21   2021     STD  LYB  16.79
2281  12/31/22   2022     STD  LYB  11.86
2282  12/31/23   2023     STD  LYB   6.50
2283  12/31/24   2024     STD  LYB   4.15

[2009 rows x 5 columns]

In [153]:
new_df.to_csv('updated_ticker_eps.csv',index=False)

# **Cleaning the Financial Ratios Dataset(obtained using Compustat Financial Ratios)**

In [154]:
financial_ratios=pd.read_csv('/content/drive/MyDrive/Financial_Ratios.csv')
financial_ratios.head()

permno       adate       qdate public_date  pe_exi    npm  opmad    roa  \
0   10104  2014-05-31  2014-11-30  2015-01-31  17.454  0.281  0.391  0.199   
1   10104  2014-05-31  2014-11-30  2015-02-28  18.258  0.281  0.391  0.199   
2   10104  2014-05-31  2014-11-30  2015-03-31  17.979  0.281  0.391  0.199   
3   10104  2014-05-31  2015-02-28  2015-04-30  18.251  0.279  0.386  0.190   
4   10104  2014-05-31  2015-02-28  2015-05-31  18.197  0.279  0.386  0.190   

     roe  de_ratio  intcov_ratio  curr_ratio TICKER  
0  0.238     0.999        14.982       3.837   ORCL  
1  0.238     0.999        14.982       3.837   ORCL  
2  0.238     0.999        14.982       3.837   ORCL  
3  0.232     1.029        14.180       3.916   ORCL  
4  0.232     1.029        14.180       3.916   ORCL

In [155]:
financial_ratios.drop(columns=['adate','qdate'],axis=1,inplace=True)

In [156]:
financial_ratios.isnull().sum()

permno             0
public_date        0
pe_exi           217
npm               21
opmad             21
roa               33
roe             1097
de_ratio           9
intcov_ratio    1928
curr_ratio      3143
TICKER             5
dtype: int64

In [157]:
null_values_ticker_count = financial_ratios[financial_ratios['TICKER'].isnull()]
null_values_ticker_count

permno public_date   pe_exi    npm  opmad    roa    roe  de_ratio  \
3840   15408  2015-09-30      NaN  0.043  0.221  0.072  0.023     1.373   
3841   15408  2015-10-31      NaN  0.043  0.221  0.072  0.023     1.373   
4290   16692  2017-07-31 -127.560 -0.017  0.100  0.086 -0.045    14.689   
5940   20057  2021-01-31   32.673  0.023  0.168  0.118  0.020     1.588   
6828   22623  2022-04-30      NaN    NaN    NaN    NaN    NaN       NaN   

      intcov_ratio  curr_ratio TICKER  
3840         2.497       1.755    NaN  
3841         2.497       1.755    NaN  
4290         1.151       2.417    NaN  
5940         4.129       1.084    NaN  
6828           NaN         NaN    NaN

In [158]:
financial_ratios[financial_ratios['permno']==15408]['TICKER'].unique()


array([nan, 'KHC'], dtype=object)

In [159]:
# prompt: Replace all the null values in the ticker column having the permno 15408 with KHC in financial_ratios

# Replace null values in 'TICKER' column for permno 15408 with 'KHC'
financial_ratios.loc[(financial_ratios['permno'] == 15408) & (financial_ratios['TICKER'].isnull()), 'TICKER'] = 'KHC'


In [160]:
financial_ratios.isnull().sum()

permno             0
public_date        0
pe_exi           217
npm               21
opmad             21
roa               33
roe             1097
de_ratio           9
intcov_ratio    1928
curr_ratio      3143
TICKER             3
dtype: int64

In [161]:
null_values_ticker_count = financial_ratios[financial_ratios['TICKER'].isnull()]
null_values_ticker_count

permno public_date   pe_exi    npm  opmad    roa    roe  de_ratio  \
4290   16692  2017-07-31 -127.560 -0.017  0.100  0.086 -0.045    14.689   
5940   20057  2021-01-31   32.673  0.023  0.168  0.118  0.020     1.588   
6828   22623  2022-04-30      NaN    NaN    NaN    NaN    NaN       NaN   

      intcov_ratio  curr_ratio TICKER  
4290         1.151       2.417    NaN  
5940         4.129       1.084    NaN  
6828           NaN         NaN    NaN

In [162]:
financial_ratios[financial_ratios['permno']==16692]
financial_ratios[financial_ratios['permno']==16692]['TICKER'].unique()

array([nan, 'GDI', 'IR'], dtype=object)

In [163]:
financial_ratios[financial_ratios['permno']==20057]['TICKER'].unique()

array([nan, 'VTRS'], dtype=object)

In [164]:
financial_ratios[financial_ratios['permno']==22623]['TICKER'].unique()

array([nan, 'CEG'], dtype=object)

In [165]:
# prompt: Replace all the null values in the ticker column having the permno 15408 with KHC in financial_ratios

# Replace null values in 'TICKER' column for permno 15408 with 'KHC'
financial_ratios.loc[(financial_ratios['permno'] == 22623) & (financial_ratios['TICKER'].isnull()), 'TICKER'] = 'CEG'
financial_ratios.loc[(financial_ratios['permno'] == 20057) & (financial_ratios['TICKER'].isnull()), 'TICKER'] = 'VTRS'


In [166]:
null_values_ticker_count=financial_ratios[financial_ratios['TICKER'].isnull()]
null_values_ticker_count

permno public_date  pe_exi    npm  opmad    roa    roe  de_ratio  \
4290   16692  2017-07-31 -127.56 -0.017    0.1  0.086 -0.045    14.689   

      intcov_ratio  curr_ratio TICKER  
4290         1.151       2.417    NaN

In [167]:
financial_ratios[financial_ratios['permno']==16692]


permno public_date   pe_exi    npm  opmad    roa    roe  de_ratio  \
4290   16692  2017-07-31 -127.560 -0.017  0.100  0.086 -0.045    14.689   
4291   16692  2017-08-31  -25.258 -0.084  0.034  0.057 -0.232     6.418   
4292   16692  2017-09-30  -29.591 -0.084  0.034  0.057 -0.232     6.418   
4293   16692  2017-10-31  -31.022 -0.084  0.034  0.057 -0.232     6.418   
4294   16692  2017-11-30  -46.300 -0.059  0.064  0.074 -0.129     4.807   
...      ...         ...      ...    ...    ...    ...    ...       ...   
4375   16692  2024-08-31   45.272  0.117  0.194  0.120  0.080     0.630   
4376   16692  2024-09-30   48.594  0.117  0.194  0.120  0.080     0.630   
4377   16692  2024-10-31   47.525  0.117  0.194  0.120  0.080     0.630   
4378   16692  2024-11-30   50.815  0.117  0.199  0.118  0.080     0.678   
4379   16692  2024-12-31   44.127  0.117  0.199  0.118  0.080     0.678   

      intcov_ratio  curr_ratio TICKER  
4290         1.151       2.417    NaN  
4291         0.424       2.455    GDI  
4292         0.424       2.455    GDI  
4293         0.424       2.455    GDI  
4294         0.937       2.469    GDI  
...            ...         ...    ...  
4375         8.308       2.243     IR  
4376         8.308       2.243     IR  
4377         8.308       2.243     IR  
4378         7.528       2.269     IR  
4379         7.528       2.269     IR  

[90 rows x 11 columns]

In [168]:
financial_ratios.loc[(financial_ratios['permno'] == 16692) & (financial_ratios['TICKER'].isnull()), 'TICKER'] = 'GDI'


In [169]:
null_values_ticker_count=financial_ratios[financial_ratios['TICKER'].isnull()]
null_values_ticker_count

Empty DataFrame
Columns: [permno, public_date, pe_exi, npm, opmad, roa, roe, de_ratio, intcov_ratio, curr_ratio, TICKER]
Index: []

In [170]:
null_value_count=financial_ratios.isnull().sum()
null_value_count

permno             0
public_date        0
pe_exi           217
npm               21
opmad             21
roa               33
roe             1097
de_ratio           9
intcov_ratio    1928
curr_ratio      3143
TICKER             0
dtype: int64

In [171]:
df

datadate  fyear datafmt  tic  epspx
0     12/31/15   2015     STD  ABT   1.73
1     12/31/16   2016     STD  ABT   0.71
2     12/31/17   2017     STD  ABT   0.20
3     12/31/18   2018     STD  ABT   1.32
4     12/31/19   2019     STD  ABT   2.07
...        ...    ...     ...  ...    ...
2279  12/31/20   2020     STD  LYB   4.25
2280  12/31/21   2021     STD  LYB  16.79
2281  12/31/22   2022     STD  LYB  11.86
2282  12/31/23   2023     STD  LYB   6.50
2283  12/31/24   2024     STD  LYB   4.15

[2009 rows x 5 columns]

In [172]:
import pandas as pd
financial_ratios['year'] = pd.to_datetime(financial_ratios['public_date']).dt.year


In [173]:
financial_ratios.head()

permno public_date  pe_exi    npm  opmad    roa    roe  de_ratio  \
0   10104  2015-01-31  17.454  0.281  0.391  0.199  0.238     0.999   
1   10104  2015-02-28  18.258  0.281  0.391  0.199  0.238     0.999   
2   10104  2015-03-31  17.979  0.281  0.391  0.199  0.238     0.999   
3   10104  2015-04-30  18.251  0.279  0.386  0.190  0.232     1.029   
4   10104  2015-05-31  18.197  0.279  0.386  0.190  0.232     1.029   

   intcov_ratio  curr_ratio TICKER  year  
0        14.982       3.837   ORCL  2015  
1        14.982       3.837   ORCL  2015  
2        14.982       3.837   ORCL  2015  
3        14.180       3.916   ORCL  2015  
4        14.180       3.916   ORCL  2015

In [174]:
df.head()

datadate  fyear datafmt  tic  epspx
0  12/31/15   2015     STD  ABT   1.73
1  12/31/16   2016     STD  ABT   0.71
2  12/31/17   2017     STD  ABT   0.20
3  12/31/18   2018     STD  ABT   1.32
4  12/31/19   2019     STD  ABT   2.07

In [175]:
df.columns.tolist()

['datadate', 'fyear', 'datafmt', 'tic', 'epspx']

In [176]:
df = df.rename(columns={'tic': 'TICKER'})


In [177]:
import numpy as np

financial_ratios['epspx'] = np.nan


for index, row in financial_ratios.iterrows():
    ticker = row['TICKER']
    year = row['year']

    matching_rows = df[(df['TICKER'] == ticker) & (df['fyear'] == year)]

    if not matching_rows.empty:
        financial_ratios.loc[index, 'epspx'] = matching_rows['epspx'].iloc[0]


In [178]:
financial_ratios.head()

permno public_date  pe_exi    npm  opmad    roa    roe  de_ratio  \
0   10104  2015-01-31  17.454  0.281  0.391  0.199  0.238     0.999   
1   10104  2015-02-28  18.258  0.281  0.391  0.199  0.238     0.999   
2   10104  2015-03-31  17.979  0.281  0.391  0.199  0.238     0.999   
3   10104  2015-04-30  18.251  0.279  0.386  0.190  0.232     1.029   
4   10104  2015-05-31  18.197  0.279  0.386  0.190  0.232     1.029   

   intcov_ratio  curr_ratio TICKER  year  epspx  
0        14.982       3.837   ORCL  2015   2.11  
1        14.982       3.837   ORCL  2015   2.11  
2        14.982       3.837   ORCL  2015   2.11  
3        14.180       3.916   ORCL  2015   2.11  
4        14.180       3.916   ORCL  2015   2.11

In [180]:
financial_ratios.to_csv('Financial_ratios_with_eps.csv')